openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Steam API"
  description: Game supplier and distributor
  contact:
    name: OpenAPI spec creator
    email: alfie.rayner30@gmail.com

servers:
  - url: https://api.steampowered.com
    description: Steam api server
tags:
  - name: Web
    description: Everything that is used to get data
    externalDocs:
      description: Find out more
      url: https://developer.valvesoftware.com/wiki/Steam_Web_API

paths:
  /ISteamNews/GetNewsForApp/v0002:
    get:
      summary: returns game news by appid.
      description: GetNewsForApp returns the latest of a game specified by its appID.
      operationId: GetNewsForApp
      tags:
        - "Web"
      parameters:
        - in: query
          name: appid
          schema:
            type: integer
          description: AppID of the game
        - in: query
          name: count
          schema:
            type: integer
          description: amount of entries returned
        - in: query
          name: maxlength
          schema:
            type: integer
          description: Max length a news entry can be
        - in: query
          name: format
          schema:
            type: string
          description: Output format. json (default), xml or vdf
      responses:
        "200":
          description: JSON object of data
          content:
            application/json:
              schema:
                type: object
                properties:
                  appnews:
                    type: object
                    properties:
                      appid:
                        type: integer
                      newsitems:
                        type: array
                        items:
                          type: object
                          properties:
                            gid:
                              type: integer
                            title:
                              type: string
                            url:
                              type: string
                            is_external_url:
                              type: boolean
                            author:
                              type: string
                            contents:
                              type: string
                            feedlabel:
                              type: string
                            date:
                              type: integer
                            feedname:
                              type: string
                            feedtype:
                              type: integer
                            appid:
                              type: integer
                            tags:
                              type: array
                              items:
                                type: string
            application/xml:
              schema:
                type: object
                xml:
                  name: "appnews"
                properties:
                  appid:
                    type: integer
                  newsitems:
                    type: object
                    properties:
                      newsitems:
                        type: array
                        items:
                          type: object
                          properties:
                            gid:
                              type: string
                            title:
                              type: string
                            url:
                              type: string
                            is_external_url:
                              type: boolean
                            author:
                              type: string
                            contents:
                              type: string
                            feedlabel:
                              type: string
                            date:
                              type: integer
                            feedname:
                              type: string
                            feedtype:
                              type: integer
                            appid:
                              type: integer
                            tags:
                              type: array
                              items:
                                type: string
                  count:
                    type: string
        "403":
          description: Using non-valid parameters
      deprecated: false

  /ISteamUserStats/GetGlobalAchievementPercentagesForApp/v0002:
    get:
      summary: Returns global achievement percentages for a game
      description: Returns on global achievements overview of a specific game in percentages
      operationId: GetGlobalAchievementPercentagesForApp
      tags:
        - "Web"
      parameters:
        - in: query
          name: gameid
          schema:
            type: integer
          description: AppID of the game you want the achievements of
        - in: query
          name: format
          schema:
            type: string
          description: Output format. json (default), xml or vdf
      responses:
        "200":
          description: JSON/XML/VDF object of data
          content:
            application/json:
              schema:
                type: object
                properties:
                  achievementpercentages:
                    type: object
                    properties:
                      achievements:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            percent:
                              type: integer
            application/xml:
              schema:
                type: object
                xml:
                  name: "achievementpercentages"
                properties:
                  achievements:
                    type: array
                    items:
                      type: object
                      properties:
                        achievement:
                          type: object
                          properties:
                            name:
                              type: string
                            percent:
                              type: integer
  /ISteamUser/GetPlayerSummaries/v0002:
    get:
      summary: Returns user data
      description: Returns on global achievements overview of a specific game in percentages
      operationId: GetPlayerSummaries
      tags:
        - "Web"
      parameters:
        - in: query
          name: key
          schema:
            type: string
          description: Your steam web api key
        - in: query
          name: steamid
          schema:
            type: integer
          description: Comma-delimited list of 64 bit Steam IDs to return profile information for. Up to 100 Steam IDs can be requested.
        - in: query
          name: format
          schema:
            type: string
          description: Output format. json (default), xml or vdf
      responses:
        "200":
          description: Some data associated with a Steam account may be hidden if the user has their profile visibility set to "Friends Only" or "Private". In that case, only public data will be returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  responses:
                    type: object
                    properties:
                      players:
                        type: array
                        items:
                          type: object
                          properties:
                            steamid:
                              type: string
                            communityvisibilitystate:
                              type: integer
                            profilestate:
                              type: integer
                            personaname:
                              type: string
                            profileurl:
                              type: string
                            avatar:
                              type: string
                            avatarmedium:
                              type: string
                            avatarfull:
                              type: string
                            avatarhash:
                              type: string
                            personastate:
                              type: integer
                            realname:
                              type: string
                            primaryclanid:
                              type: string
                            timecreated:
                              type: integer
                            personastateflags:
                              type: integer
                            loccountrycode:
                              type: string
                            locstatecode:
                              type: string
                            loccityid:
                              type: string
            application/xml:
              schema: 
                type: object
                xml:
                  name: "Response"
                properties:
                  players:
                    type: object
                    properties:
                      player:
                        type: array
                        items:
                          type: object
                          properties:
                            steamid:
                              type: string
                            communityvisibilitystate:
                              type: integer
                            profilestate:
                              type: integer
                            personaname:
                              type: string
                            profileurl:
                              type: string
                            avatar:
                              type: string
                            avatarmedium:
                              type: string
                            avatarfull:
                              type: string
                            avatarhash:
                              type: string
                            personastate:
                              type: integer
                            realname:
                              type: string
                            primaryclanid:
                              type: string
                            timecreated:
                              type: integer
                            personastateflags:
                              type: integer
                            loccountrycode:
                              type: string
                            locstatecode:
                              type: string
                            loccityid:
                              type: string